# Generated by Django 5.1.2 on 2024-11-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_elaboracion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='diseno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano',
            field=models.CharField(max_length=100),
        ),
    ]
